/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as AuthSignupImport } from './routes/auth/signup'
import { Route as AuthLoginImport } from './routes/auth/login'
import { Route as PostForumIndexImport } from './routes/post/forum/index'
import { Route as PostReadidIndexImport } from './routes/post/read/[id]/index'
import { Route as PostForumslugIndexImport } from './routes/post/forum/[slug]/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthSignupRoute = AuthSignupImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRoute,
} as any)

const AuthLoginRoute = AuthLoginImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRoute,
} as any)

const PostForumIndexRoute = PostForumIndexImport.update({
  id: '/post/forum/',
  path: '/post/forum/',
  getParentRoute: () => rootRoute,
} as any)

const PostReadidIndexRoute = PostReadidIndexImport.update({
  id: '/post/read/[id]/',
  path: '/post/read/[id]/',
  getParentRoute: () => rootRoute,
} as any)

const PostForumslugIndexRoute = PostForumslugIndexImport.update({
  id: '/post/forum/[slug]/',
  path: '/post/forum/[slug]/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginImport
      parentRoute: typeof rootRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupImport
      parentRoute: typeof rootRoute
    }
    '/post/forum/': {
      id: '/post/forum/'
      path: '/post/forum'
      fullPath: '/post/forum'
      preLoaderRoute: typeof PostForumIndexImport
      parentRoute: typeof rootRoute
    }
    '/post/forum/[slug]/': {
      id: '/post/forum/[slug]/'
      path: '/post/forum/[slug]'
      fullPath: '/post/forum/[slug]'
      preLoaderRoute: typeof PostForumslugIndexImport
      parentRoute: typeof rootRoute
    }
    '/post/read/[id]/': {
      id: '/post/read/[id]/'
      path: '/post/read/[id]'
      fullPath: '/post/read/[id]'
      preLoaderRoute: typeof PostReadidIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/post/forum': typeof PostForumIndexRoute
  '/post/forum/[slug]': typeof PostForumslugIndexRoute
  '/post/read/[id]': typeof PostReadidIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/post/forum': typeof PostForumIndexRoute
  '/post/forum/[slug]': typeof PostForumslugIndexRoute
  '/post/read/[id]': typeof PostReadidIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/post/forum/': typeof PostForumIndexRoute
  '/post/forum/[slug]/': typeof PostForumslugIndexRoute
  '/post/read/[id]/': typeof PostReadidIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth/login'
    | '/auth/signup'
    | '/post/forum'
    | '/post/forum/[slug]'
    | '/post/read/[id]'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/auth/signup'
    | '/post/forum'
    | '/post/forum/[slug]'
    | '/post/read/[id]'
  id:
    | '__root__'
    | '/'
    | '/auth/login'
    | '/auth/signup'
    | '/post/forum/'
    | '/post/forum/[slug]/'
    | '/post/read/[id]/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
  PostForumIndexRoute: typeof PostForumIndexRoute
  PostForumslugIndexRoute: typeof PostForumslugIndexRoute
  PostReadidIndexRoute: typeof PostReadidIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
  PostForumIndexRoute: PostForumIndexRoute,
  PostForumslugIndexRoute: PostForumslugIndexRoute,
  PostReadidIndexRoute: PostReadidIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/auth/login",
        "/auth/signup",
        "/post/forum/",
        "/post/forum/[slug]/",
        "/post/read/[id]/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/auth/login": {
      "filePath": "auth/login.tsx"
    },
    "/auth/signup": {
      "filePath": "auth/signup.tsx"
    },
    "/post/forum/": {
      "filePath": "post/forum/index.tsx"
    },
    "/post/forum/[slug]/": {
      "filePath": "post/forum/[slug]/index.tsx"
    },
    "/post/read/[id]/": {
      "filePath": "post/read/[id]/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
